# Generated by Django 3.2.3 on 2024-07-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20240711_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='client',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='client',
            name='genotype',
        ),
        migrations.RemoveField(
            model_name='client',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='height',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='weight',
        ),
    ]
