# Generated by Django 3.2.3 on 2024-07-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20240711_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
